### ISSUE TITLE
Unable to convert to PDF

### ISSUE THREAD

**Issue by rishab-yumist** [jbach/csv-report#1]
Hello,

@jbach Could you help me on this?

On passing a csv file, the output PDF file is empty.

  var csvReport = require('csv-report');
          var options = {
              file: "assets/sheets/csv/station/station1469601320388.csv",
              out: "assets/sheets/pdf/" + task.output_name
          };

```
var report = new csvReport(options)
          .render(function(err, pdfPath){
            console.log("Render called.");
          });

          report.on('error', function(err){
            console.log("Error");
            console.log(err);
            return pdfcb({"statusCode": 200, "errorMessage": "Error converting to pdf."});
          })
          report.on('done', function(outputPath){
            console.log("Output");
            console.log(outputPath);
            return pdfcb(null,'PDF was written to ' + outputPath);
          })
```

Render function isn't called. 
But done function callback works.

What might be the issue?

**Comment by jbach** [comment]
Hey Rishab,
I just pushed 0.2.2 which fixes the missing callback call from `render()`.

As for the empty output, you can try checking the log via `report.on('log')` to see whats going on. Make sure, your .csv is formatted correctly.

If you input CSV like this:

| "Project"       | "Task"        | "Date"       | "Start"               | "End"                 | "Duration" | "Comment" | 
|-----------------|---------------|--------------|-----------------------|-----------------------|------------|-----------| 
| "MyProjectName" | "First Task"  | "2016-06-26" | "2016-06-26 14:25:29" | "2016-06-26 15:50:12" | "01:24:42" | ""        | 
| "MyProjectName" | "Second Task" | "2016-06-26" | "2016-06-26 16:23:07" | "2016-06-26 18:06:05" | "01:42:58" | ""        | 


you will get a pdf like this: [test.pdf](https://github.com/jbach/csv-report/files/385615/test.pdf)

**Comment by rishab-yumist** [comment]
Hey @jbach,

My csv looks something like this. Can I just mention the input file name and output file name and it'll automatically convert to pdf?

![screen shot 2016-07-27 at 1 57 57 pm](https://cloud.githubusercontent.com/assets/13828707/17168825/261ac26e-5402-11e6-9874-762c177c305b.png)

**Comment by rishab-yumist** [comment]
Hey @jbach,

Got an error now using the same code.

![screen shot 2016-07-27 at 2 01 40 pm](https://cloud.githubusercontent.com/assets/13828707/17168943/be3e3378-5402-11e6-8f5d-7d544289560c.png)

**Comment by jbach** [comment]
Hey @rishab-yumist,
I think you should use a different package as `csv-report` covers a very narrow use-case: Converting time tracking data from an app like [TimeTracker](https://code.google.com/archive/p/time-tracker-mac/) into a formatted pdf that adds up the time spent on tasks/projects.

You can try parsing your csv with [csv-parser](https://github.com/mafintosh/csv-parser) and then rendering your desired output either via [pdfkit](http://pdfkit.org) or, if you want to render a HTML template, [html-pdf](https://github.com/marcbachmann/node-html-pdf).

**Comment by rishab-yumist** [comment]
Hey @jbach ,

Okay thanks. Though the issue in other packages is laying down the table borders and stuff. I was hoping this package would render it directly to pdf. 

Anyway, thanks :)
